server:
  port: 8001
spring:
  application:
    name: payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率介于0-1之间，则表示全部采样
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.liutf.entity
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment1
    prefer-ip-address: true
#    # 心跳检测与续约时间 尽量设置小点 保证服务关闭后注册中心即使剔除
#    #eureka客户端向服务器端发送心跳的时间间隔 单位秒 默认30s
#    lease-expiration-duration-in-seconds: 30
#    # eureka服务器在收到最后一次心跳等等时间上限 单位秒 默认90s 超时将剔除
#    lease-renewal-interval-in-seconds: 90