server:
  port: 8001

spring:
  application:
    name: cloud-provider-hygtrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: hygtrixpayment
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true